"""
certificate_engine.py — ML Guard Governance Certificate Engine

Generates cryptographically-verifiable compliance certificates
from GovernanceEngine scores. Provides live certificate validity
checking that tracks post-issuance drift events.
"""
from __future__ import annotations

import hashlib
import logging
from dataclasses import dataclass
from datetime import datetime
from typing import Any, List, Optional

from sqlalchemy.orm import Session

from app.services.governance_engine import GovernanceEngine, GovernanceScoreResult

logger = logging.getLogger(__name__)


# ─── Result Types ─────────────────────────────────────────────────────────────

@dataclass
class CertValidityResult:
    cert_hash: str
    valid: bool
    issued_at: Optional[str]
    verdict: Optional[str]
    overall_score: Optional[float]
    is_revoked: bool
    revocation_reason: Optional[str]
    drift_events_since_issue: int
    still_compliant: bool
    message: str


# ─── Certificate Engine ───────────────────────────────────────────────────────

class CertificateEngine:
    """
    Generates compliance certificates from GovernanceEngine scores.
    This is the physical proof-of-governance that auditors and CTOs need.
    Certificates are live — they track post-issuance drift events
    and expose a public /verify endpoint so auditors can check validity.
    """

    def generate_cert_hash(
        self,
        model_id: str,
        score: float,
        timestamp: datetime,
    ) -> str:
        """
        Generate a deterministic SHA-256 certificate hash.
        Hash encodes model_id + score + timestamp for tamper detection.
        """
        raw = f"{model_id}:{score:.4f}:{timestamp.isoformat()}"
        return hashlib.sha256(raw.encode("utf-8")).hexdigest()

    def _generate_executive_summary(
        self,
        model_id: str,
        governance_result: GovernanceScoreResult,
    ) -> str:
        """
        Generate a professional executive summary for the report card.
        Calls claude-haiku if ANTHROPIC_API_KEY is set; falls back to template.
        """
        # Template fallback — always works without LLM
        score = governance_result.overall_score
        live_score = governance_result.live_score
        verdict = governance_result.verdict
        component_lines = "\n".join(
            f"  - {k.replace('_', ' ').title()}: {v:.1f}/100 (weight {w:.0%})"
            for (k, v), (_, w) in zip(
                governance_result.component_scores.items(),
                governance_result.component_weights.items()
            )
        )

        template = (
            f"GOVERNANCE COMPLIANCE CERTIFICATE — ML Guard v7.2\n\n"
            f"Model: {model_id}\n"
            f"Issued: {governance_result.computed_at.strftime('%Y-%m-%d %H:%M UTC')}\n"
            f"Verdict: {verdict}\n"
            f"Audit Score: {score:.1f}/100\n"
            f"Live Score (decay applied): {live_score:.1f}/100\n\n"
            f"COMPONENT BREAKDOWN:\n{component_lines}\n\n"
            f"RECOMMENDATIONS:\n" +
            "\n".join(f"  • {r}" for r in governance_result.recommendations) +
            f"\n\nThis certificate was generated by ML Guard and reflects the model's "
            f"governance posture at time of audit. The live score continues to be "
            f"updated based on production monitoring signals and will be marked "
            f"non-compliant if significant drift or degradation is detected."
        )

        # Try optional LLM enrichment
        try:
            import os
            key = os.getenv("ANTHROPIC_API_KEY")
            if key:
                import anthropic
                client = anthropic.Anthropic(api_key=key)
                msg = client.messages.create(
                    model="claude-haiku-20240307",
                    max_tokens=400,
                    messages=[{
                        "role": "user",
                        "content": (
                            f"Write a concise, professional 3-sentence executive summary for "
                            f"a governance certificate. Model '{model_id}' scored {score:.1f}/100 "
                            f"(verdict: {verdict}). Include key risks and recommendations.\n\n"
                            f"Component scores: {governance_result.component_scores}"
                        )
                    }]
                )
                return msg.content[0].text
        except Exception as e:
            logger.debug(f"llm_summary_fallback reason={str(e)}")

        return template

    def generate_report_card(
        self,
        model_id: str,
        governance_result: GovernanceScoreResult,
        db: Session,
    ) -> Any:
        """
        Create ReportCard DB record.
        Generates cert hash, executive summary, and metric snapshot.
        Returns the persisted ReportCard object.
        """
        from app.db.models import ReportCard

        cert_hash = self.generate_cert_hash(
            model_id,
            governance_result.overall_score,
            governance_result.computed_at,
        )

        # Check for existing cert with same hash (idempotent)
        existing = db.query(ReportCard).filter(ReportCard.cert_hash == cert_hash).first()
        if existing:
            logger.info(f"cert_already_exists cert_hash={cert_hash}")
            return existing

        executive_summary = self._generate_executive_summary(model_id, governance_result)

        metric_snapshots = {
            "component_scores": governance_result.component_scores,
            "component_weights": governance_result.component_weights,
            "gate_results": [
                {
                    "metric": gr.metric,
                    "value": gr.value,
                    "threshold": gr.threshold,
                    "verdict": gr.verdict,
                    "message": gr.message,
                }
                for gr in governance_result.gate_results
            ],
            "drift_penalty": governance_result.drift_penalty,
            "perf_penalty": governance_result.perf_penalty,
            "live_score": governance_result.live_score,
            "recommendations": governance_result.recommendations,
        }

        # Resolve model UUID for the FK — try to look up by model_id string
        model_fk = None
        try:
            import uuid
            from app.db.models import Model
            # Try direct UUID parse
            model_fk = uuid.UUID(str(model_id))
            # Verify it exists
            exists = db.query(Model.id).filter(Model.id == model_fk).scalar()
            if not exists:
                model_fk = None
        except (ValueError, Exception):
            try:
                from app.db.models import Model
                m = db.query(Model).filter(Model.name == model_id).first()
                if m:
                    model_fk = m.id
            except Exception:
                pass

        if model_fk is None:
            # Cannot create report card without valid model FK
            raise ValueError(
                f"Cannot generate report card: model '{model_id}' not found in registry. "
                f"Register the model first at POST /api/v1/models."
            )

        report_card = ReportCard(
            model_id=model_fk,
            cert_hash=cert_hash,
            issued_at=governance_result.computed_at,
            overall_score=governance_result.overall_score,
            verdict=governance_result.verdict,
            executive_summary=executive_summary,
            metric_snapshots=metric_snapshots,
            is_revoked=False,
        )

        db.add(report_card)
        db.commit()
        db.refresh(report_card)

        logger.info(
            "report_card_generated",
            model_id=model_id,
            cert_hash=cert_hash,
            verdict=governance_result.verdict,
            score=governance_result.overall_score,
        )

        return report_card

    def check_certificate_validity(
        self,
        cert_hash: str,
        db: Session,
    ) -> CertValidityResult:
        """
        Public endpoint logic — no auth required.
        Checks if a certificate is valid, revoked, or no longer compliant.
        Counts HIGH/CRITICAL drift events since the cert was issued.

        This is the "live certificate" concept — a cert issued at score 92
        may now show as non-compliant if production drift was detected since
        issuance. Auditors see this in real time.
        """
        from app.db.models import ReportCard, DriftReport

        card = db.query(ReportCard).filter(ReportCard.cert_hash == cert_hash).first()

        if not card:
            return CertValidityResult(
                cert_hash=cert_hash,
                valid=False,
                issued_at=None,
                verdict=None,
                overall_score=None,
                is_revoked=False,
                revocation_reason=None,
                drift_events_since_issue=0,
                still_compliant=False,
                message="Certificate not found. Invalid or tampered hash.",
            )

        if card.is_revoked:
            return CertValidityResult(
                cert_hash=cert_hash,
                valid=False,
                issued_at=card.issued_at.isoformat() if card.issued_at else None,
                verdict=card.verdict,
                overall_score=card.overall_score,
                is_revoked=True,
                revocation_reason=card.revocation_reason,
                drift_events_since_issue=0,
                still_compliant=False,
                message=f"Certificate REVOKED: {card.revocation_reason or 'No reason given.'}",
            )

        # Count HIGH/CRITICAL drift events since cert was issued
        drift_events_since_issue = 0
        still_compliant = True
        try:
            model_id_str = str(card.model_id)
            issued_at = card.issued_at or datetime.utcnow()

            high_drift_count = (
                db.query(DriftReport)
                .filter(
                    DriftReport.model_id == model_id_str,
                    DriftReport.created_at >= issued_at,
                    DriftReport.drift_detected == True,
                    DriftReport.alert_triggered == True,
                )
                .count()
            )
            drift_events_since_issue = high_drift_count
            still_compliant = high_drift_count == 0
        except Exception as e:
            logger.warning(f"drift_event_check_failed error={str(e)}")

        message = (
            f"Certificate VALID — Issued {card.issued_at.strftime('%Y-%m-%d') if card.issued_at else 'N/A'}, "
            f"Score {card.overall_score:.1f}, Verdict {card.verdict}."
            if still_compliant
            else
            f"Certificate ISSUED but {drift_events_since_issue} HIGH/CRITICAL drift event(s) detected "
            f"since issuance — model may no longer be compliant. Re-audit recommended."
        )

        return CertValidityResult(
            cert_hash=cert_hash,
            valid=True,
            issued_at=card.issued_at.isoformat() if card.issued_at else None,
            verdict=card.verdict,
            overall_score=card.overall_score,
            is_revoked=False,
            revocation_reason=None,
            drift_events_since_issue=drift_events_since_issue,
            still_compliant=still_compliant,
            message=message,
        )

