"""Add user_id to audit_logs

Revision ID: 13a17fcfdefd
Revises: e0c1f92c5e13
Create Date: 2026-04-29 00:32:19.100308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.db.models


# revision identifiers, used by Alembic.
revision: str = '13a17fcfdefd'
down_revision: Union[str, Sequence[str], None] = 'e0c1f92c5e13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', app.db.models.UUID(), nullable=True))
        batch_op.create_foreign_key('fk_audit_logs_user_id', 'users', ['user_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
