"""Initial schema

Revision ID: e0c1f92c5e13
Revises: 
Create Date: 2026-04-29 00:26:55.918985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.db.models


# revision identifiers, used by Alembic.
revision: str = 'e0c1f92c5e13'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dataset_registry',
    sa.Column('id', app.db.models.UUID(), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('source_uri', sa.String(length=1024), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('column_names', app.db.models.PortableJSON(), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('drift_reports',
    sa.Column('id', app.db.models.UUID(), nullable=False),
    sa.Column('model_id', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('reference_window_start', sa.DateTime(), nullable=True),
    sa.Column('reference_window_end', sa.DateTime(), nullable=True),
    sa.Column('current_window_start', sa.DateTime(), nullable=True),
    sa.Column('current_window_end', sa.DateTime(), nullable=True),
    sa.Column('feature_results', app.db.models.PortableJSON(), nullable=False),
    sa.Column('overall_drift_score', sa.Float(), nullable=False),
    sa.Column('drift_detected', sa.Boolean(), nullable=True),
    sa.Column('method', sa.String(length=50), nullable=True),
    sa.Column('sample_count', sa.Integer(), nullable=True),
    sa.Column('alert_triggered', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drift_reports_created_at'), 'drift_reports', ['created_at'], unique=False)
    op.create_index(op.f('ix_drift_reports_model_id'), 'drift_reports', ['model_id'], unique=False)
    op.create_index('ix_driftreport_model_ts', 'drift_reports', ['model_id', 'created_at'], unique=False)
    op.create_table('embedding_batches',
    sa.Column('id', app.db.models.UUID(), nullable=False),
    sa.Column('model_id', sa.String(length=255), nullable=False),
    sa.Column('batch_id', sa.String(length=255), nullable=False),
    sa.Column('embeddings', app.db.models.PortableJSON(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_embedding_batches_batch_id'), 'embedding_batches', ['batch_id'], unique=False)
    op.create_index(op.f('ix_embedding_batches_model_id'), 'embedding_batches', ['model_id'], unique=False)
    op.create_index(op.f('ix_embedding_batches_timestamp'), 'embedding_batches', ['timestamp'], unique=False)
    op.create_table('performance_snapshots',
    sa.Column('id', app.db.models.UUID(), nullable=False),
    sa.Column('model_id', sa.String(length=255), nullable=False),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.Column('window_start', sa.DateTime(), nullable=True),
    sa.Column('window_end', sa.DateTime(), nullable=True),
    sa.Column('task_type', sa.String(length=50), nullable=True),
    sa.Column('metrics', app.db.models.PortableJSON(), nullable=False),
    sa.Column('baseline_metrics', app.db.models.PortableJSON(), nullable=True),
    sa.Column('degradation_report', app.db.models.PortableJSON(), nullable=True),
    sa.Column('sample_count', sa.Integer(), nullable=True),
    sa.Column('labeled_count', sa.Integer(), nullable=True),
    sa.Column('label_coverage_pct', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_performance_snapshots_computed_at'), 'performance_snapshots', ['computed_at'], unique=False)
    op.create_index(op.f('ix_performance_snapshots_model_id'), 'performance_snapshots', ['model_id'], unique=False)
    op.create_index('ix_perfsnapshot_model_ts', 'performance_snapshots', ['model_id', 'computed_at'], unique=False)
    op.create_table('rag_traces',
    sa.Column('id', app.db.models.UUID(), nullable=False),
    sa.Column('model_id', sa.String(length=255), nullable=False),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('retrieved_chunks', app.db.models.PortableJSON(), nullable=False),
    sa.Column('retrieved_doc_ids', app.db.models.PortableJSON(), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('context_relevance', sa.Float(), nullable=True),
    sa.Column('grounding_fidelity', sa.Float(), nullable=True),
    sa.Column('hallucination_risk', sa.String(length=50), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rag_traces_model_id'), 'rag_traces', ['model_id'], unique=False)
    op.create_index(op.f('ix_rag_traces_timestamp'), 'rag_traces', ['timestamp'], unique=False)
    op.create_table('retraining_policies',
    sa.Column('id', app.db.models.UUID(), nullable=False),
    sa.Column('model_id', sa.String(length=255), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('trigger_conditions', app.db.models.PortableJSON(), nullable=False),
    sa.Column('retrain_action', app.db.models.PortableJSON(), nullable=False),
    sa.Column('last_triggered_at', sa.DateTime(), nullable=True),
    sa.Column('trigger_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_retraining_policies_model_id'), 'retraining_policies', ['model_id'], unique=True)
    op.create_table('stream_drift_records',
    sa.Column('id', app.db.models.UUID(), nullable=False),
    sa.Column('model_id', sa.String(length=255), nullable=False),
    sa.Column('window_psi', sa.Float(), nullable=False),
    sa.Column('window_jsd', sa.Float(), nullable=True),
    sa.Column('trend', sa.String(length=20), nullable=True),
    sa.Column('alert', sa.Boolean(), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('window_size', sa.Integer(), nullable=True),
    sa.Column('total_events', sa.Integer(), nullable=True),
    sa.Column('adaptive_threshold', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stream_drift_records_model_id'), 'stream_drift_records', ['model_id'], unique=False)
    op.create_table('subscription_plans',
    sa.Column('id', app.db.models.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('price_monthly_usd', sa.Integer(), nullable=True),
    sa.Column('predictions_per_month', sa.Integer(), nullable=True),
    sa.Column('models_limit', sa.Integer(), nullable=True),
    sa.Column('reports_per_month', sa.Integer(), nullable=True),
    sa.Column('compliance_packs_limit', sa.Integer(), nullable=True),
    sa.Column('guardrail_eval_limit', sa.Integer(), nullable=True),
    sa.Column('is_custom_price', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('organizations',
    sa.Column('id', app.db.models.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('plan', sa.String(length=50), nullable=True),
    sa.Column('stripe_customer_id', sa.String(length=255), nullable=True),
    sa.Column('stripe_subscription_id', sa.String(length=255), nullable=True),
    sa.Column('subscription_status', sa.String(length=50), nullable=True),
    sa.Column('plan_id', app.db.models.UUID(), nullable=True),
    sa.Column('settings', app.db.models.PortableJSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['subscription_plans.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=True)
    op.create_index(op.f('ix_organizations_stripe_customer_id'), 'organizations', ['stripe_customer_id'], unique=False)
    op.create_table('retraining_events',
    sa.Column('id', app.db.models.UUID(), nullable=False),
    sa.Column('policy_id', app.db.models.UUID(), nullable=False),
    sa.Column('model_id', sa.String(length=255), nullable=False),
    sa.Column('triggered_at', sa.DateTime(), nullable=True),
    sa.Column('triggered_conditions', app.db.models.PortableJSON(), nullable=False),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('action_result', sa.String(length=50), nullable=False),
    sa.Column('action_error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['policy_id'], ['retraining_policies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_retraining_events_model_id'), 'retraining_events', ['model_id'], unique=False)
    op.create_index(op.f('ix_retraining_events_policy_id'), 'retraining_events', ['policy_id'], unique=False)
    op.create_table('alert_rules',
    sa.Column('id', app.db.models.UUID(), nullable=False),
    sa.Column('org_id', app.db.models.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('condition', app.db.models.PortableJSON(), nullable=False),
    sa.Column('channels', app.db.models.PortableJSON(), nullable=False),
    sa.Column('webhook_url', sa.String(length=1024), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_rules_org_id'), 'alert_rules', ['org_id'], unique=False)
    op.create_table('api_keys',
    sa.Column('id', app.db.models.UUID(), nullable=False),
    sa.Column('org_id', app.db.models.UUID(), nullable=False),
    sa.Column('key_hash', sa.String(length=128), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('scopes', app.db.models.PortableJSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('rate_limit_rpm', sa.Integer(), nullable=True),
    sa.Column('request_count', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_used', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_keys_key_hash'), 'api_keys', ['key_hash'], unique=True)
    op.create_index(op.f('ix_api_keys_org_id'), 'api_keys', ['org_id'], unique=False)
    op.create_table('ci_integrations',
    sa.Column('id', app.db.models.UUID(), nullable=False),
    sa.Column('org_id', app.db.models.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('repo_url', sa.String(length=1024), nullable=True),
    sa.Column('access_token_hash', sa.String(length=256), nullable=True),
    sa.Column('webhook_secret', sa.String(length=256), nullable=True),
    sa.Column('settings', app.db.models.PortableJSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ci_integrations_org_id'), 'ci_integrations', ['org_id'], unique=False)
    op.create_table('environments',
    sa.Column('id', app.db.models.UUID(), nullable=False),
    sa.Column('org_id', app.db.models.UUID(), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('config', app.db.models.PortableJSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_environments_org_id'), 'environments', ['org_id'], unique=False)
    op.create_table('policy_rules',
    sa.Column('id', app.db.models.UUID(), nullable=False),
    sa.Column('org_id', app.db.models.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('rules_json', app.db.models.PortableJSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policy_rules_org_id'), 'policy_rules', ['org_id'], unique=False)
    op.create_table('users',
    sa.Column('id', app.db.models.UUID(), nullable=False),
    sa.Column('org_id', app.db.models.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('auth_provider', sa.String(length=50), nullable=True),
    sa.Column('auth_id', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=512), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_org_id'), 'users', ['org_id'], unique=False)
    op.create_table('agents',
    sa.Column('id', app.db.models.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('allowed_tools', app.db.models.PortableJSON(), nullable=True),
    sa.Column('sensitive_topics', app.db.models.PortableJSON(), nullable=True),
    sa.Column('step_sla_ms', sa.Integer(), nullable=True),
    sa.Column('owner_key_id', app.db.models.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_key_id'], ['api_keys.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_logs',
    sa.Column('id', app.db.models.UUID(), nullable=False),
    sa.Column('org_id', app.db.models.UUID(), nullable=True),
    sa.Column('actor_key_id', app.db.models.UUID(), nullable=True),
    sa.Column('actor_ip', sa.String(length=45), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=True),
    sa.Column('resource_id', sa.String(length=64), nullable=True),
    sa.Column('payload_hash', sa.String(length=64), nullable=True),
    sa.Column('result', sa.String(length=20), nullable=True),
    sa.Column('details', app.db.models.PortableJSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['actor_key_id'], ['api_keys.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_org_id'), 'audit_logs', ['org_id'], unique=False)
    op.create_table('credential_configs',
    sa.Column('id', app.db.models.UUID(), nullable=False),
    sa.Column('connector_type', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('encrypted_config', sa.Text(), nullable=False),
    sa.Column('created_by_key_id', app.db.models.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_key_id'], ['api_keys.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('llm_scan_records',
    sa.Column('id', app.db.models.UUID(), nullable=False),
    sa.Column('prompt_hash', sa.String(length=64), nullable=False),
    sa.Column('response_hash', sa.String(length=64), nullable=False),
    sa.Column('prompt_text', sa.Text(), nullable=True),
    sa.Column('response_text', sa.Text(), nullable=True),
    sa.Column('results_json', app.db.models.PortableJSON(), nullable=False),
    sa.Column('llm_risk_score', sa.Float(), nullable=True),
    sa.Column('llm_risk_level', sa.String(length=20), nullable=True),
    sa.Column('toxicity_score', sa.Float(), nullable=True),
    sa.Column('hallucination_risk', sa.Float(), nullable=True),
    sa.Column('injection_flag', sa.Boolean(), nullable=True),
    sa.Column('stability_score', sa.Float(), nullable=True),
    sa.Column('triggered_by', app.db.models.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['triggered_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_llm_scan_records_prompt_hash'), 'llm_scan_records', ['prompt_hash'], unique=False)
    op.create_table('model_contracts',
    sa.Column('id', app.db.models.UUID(), nullable=False),
    sa.Column('model_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('promises', app.db.models.PortableJSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('breach_grace_period_minutes', sa.Integer(), nullable=True),
    sa.Column('breach_window_minutes', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', app.db.models.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_contract_model_active', 'model_contracts', ['model_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_model_contracts_model_id'), 'model_contracts', ['model_id'], unique=False)
    op.create_table('policy_versions',
    sa.Column('id', app.db.models.UUID(), nullable=False),
    sa.Column('org_id', app.db.models.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('config', app.db.models.PortableJSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_by', app.db.models.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policy_versions_org_id'), 'policy_versions', ['org_id'], unique=False)
    op.create_table('projects',
    sa.Column('id', app.db.models.UUID(), nullable=False),
    sa.Column('org_id', app.db.models.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by', app.db.models.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_org_id'), 'projects', ['org_id'], unique=False)
    op.create_table('usage_events',
    sa.Column('id', app.db.models.UUID(), nullable=False),
    sa.Column('org_id', app.db.models.UUID(), nullable=False),
    sa.Column('api_key_id', app.db.models.UUID(), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('metadata_json', app.db.models.PortableJSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['api_key_id'], ['api_keys.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usage_events_event_type'), 'usage_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_usage_events_org_id'), 'usage_events', ['org_id'], unique=False)
    op.create_index(op.f('ix_usage_events_timestamp'), 'usage_events', ['timestamp'], unique=False)
    op.create_table('agent_traces',
    sa.Column('id', app.db.models.UUID(), nullable=False),
    sa.Column('agent_id', app.db.models.UUID(), nullable=False),
    sa.Column('session_id', sa.String(length=128), nullable=False),
    sa.Column('trace_index', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('step_type', sa.String(length=50), nullable=True),
    sa.Column('input_summary', sa.String(length=64), nullable=True),
    sa.Column('output_summary', sa.String(length=64), nullable=True),
    sa.Column('tool_name', sa.String(length=255), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('policy_violations', app.db.models.PortableJSON(), nullable=True),
    sa.Column('risk_score', sa.Integer(), nullable=True),
    sa.Column('flagged', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_traces_agent_id'), 'agent_traces', ['agent_id'], unique=False)
    op.create_index(op.f('ix_agent_traces_session_id'), 'agent_traces', ['session_id'], unique=False)
    op.create_table('contract_breaches',
    sa.Column('id', app.db.models.UUID(), nullable=False),
    sa.Column('contract_id', app.db.models.UUID(), nullable=False),
    sa.Column('model_id', sa.String(length=255), nullable=False),
    sa.Column('promise_name', sa.String(length=255), nullable=False),
    sa.Column('promise_type', sa.String(length=50), nullable=False),
    sa.Column('expected', sa.String(length=255), nullable=True),
    sa.Column('actual', sa.String(length=255), nullable=True),
    sa.Column('prediction_log_id', app.db.models.UUID(), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['model_contracts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_breach_model_ts', 'contract_breaches', ['model_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_contract_breaches_contract_id'), 'contract_breaches', ['contract_id'], unique=False)
    op.create_index(op.f('ix_contract_breaches_model_id'), 'contract_breaches', ['model_id'], unique=False)
    op.create_table('models',
    sa.Column('id', app.db.models.UUID(), nullable=False),
    sa.Column('project_id', app.db.models.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('provider', sa.String(length=255), nullable=False),
    sa.Column('fingerprint', sa.String(length=128), nullable=True),
    sa.Column('metadata_json', app.db.models.PortableJSON(), nullable=True),
    sa.Column('complexity', app.db.models.PortableJSON(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('parent_model_id', app.db.models.UUID(), nullable=True),
    sa.Column('risk_tier', sa.String(length=20), nullable=True),
    sa.Column('risk_tier_justification', sa.Text(), nullable=True),
    sa.Column('use_case_category', sa.String(length=100), nullable=True),
    sa.Column('business_owner', sa.String(length=255), nullable=True),
    sa.Column('technical_owner', sa.String(length=255), nullable=True),
    sa.Column('deployment_environment', sa.String(length=50), nullable=True),
    sa.Column('first_deployed_at', sa.DateTime(), nullable=True),
    sa.Column('regulatory_jurisdictions', app.db.models.PortableJSON(), nullable=True),
    sa.Column('model_type', sa.String(length=50), nullable=True),
    sa.Column('training_data_sensitivity', sa.String(length=50), nullable=True),
    sa.Column('last_validated_at', sa.DateTime(), nullable=True),
    sa.Column('next_validation_due_at', sa.DateTime(), nullable=True),
    sa.Column('validation_frequency_days', sa.Integer(), nullable=True),
    sa.Column('artifact_url', sa.String(length=1024), nullable=True),
    sa.Column('artifact_size', sa.BigInteger(), nullable=True),
    sa.Column('artifact_storage_provider', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', app.db.models.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['parent_model_id'], ['models.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_models_fingerprint'), 'models', ['fingerprint'], unique=False)
    op.create_index(op.f('ix_models_name'), 'models', ['name'], unique=False)
    op.create_index(op.f('ix_models_project_id'), 'models', ['project_id'], unique=False)
    op.create_table('aibom',
    sa.Column('id', app.db.models.UUID(), nullable=False),
    sa.Column('model_id', app.db.models.UUID(), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.Column('schema_version', sa.String(length=10), nullable=True),
    sa.Column('base_model', app.db.models.PortableJSON(), nullable=False),
    sa.Column('training_datasets', app.db.models.PortableJSON(), nullable=False),
    sa.Column('dependencies', app.db.models.PortableJSON(), nullable=False),
    sa.Column('training_framework', app.db.models.PortableJSON(), nullable=False),
    sa.Column('aibom_hash', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aibom_aibom_hash'), 'aibom', ['aibom_hash'], unique=False)
    op.create_index(op.f('ix_aibom_model_id'), 'aibom', ['model_id'], unique=False)
    op.create_table('alerts',
    sa.Column('id', app.db.models.UUID(), nullable=False),
    sa.Column('model_id', app.db.models.UUID(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('alert_type', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('endpoint', sa.String(length=255), nullable=True),
    sa.Column('payload_hash', sa.String(length=64), nullable=True),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('key_id', app.db.models.UUID(), nullable=True),
    sa.Column('details', app.db.models.PortableJSON(), nullable=True),
    sa.ForeignKeyConstraint(['key_id'], ['api_keys.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_model_id'), 'alerts', ['model_id'], unique=False)
    op.create_index(op.f('ix_alerts_timestamp'), 'alerts', ['timestamp'], unique=False)
    op.create_table('datasets',
    sa.Column('id', app.db.models.UUID(), nullable=False),
    sa.Column('model_id', app.db.models.UUID(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('metadata_json', app.db.models.PortableJSON(), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('fingerprint', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_datasets_model_id'), 'datasets', ['model_id'], unique=False)
    op.create_table('guardrail_configs',
    sa.Column('id', app.db.models.UUID(), nullable=False),
    sa.Column('model_id', app.db.models.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('enabled_input_checks', app.db.models.PortableJSON(), nullable=False),
    sa.Column('enabled_output_checks', app.db.models.PortableJSON(), nullable=False),
    sa.Column('action_on_block', sa.String(length=50), nullable=True),
    sa.Column('fallback_response', sa.Text(), nullable=True),
    sa.Column('allowed_topics', app.db.models.PortableJSON(), nullable=False),
    sa.Column('blocked_topics', app.db.models.PortableJSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_guardrail_configs_model_id'), 'guardrail_configs', ['model_id'], unique=False)
    op.create_table('jobs',
    sa.Column('id', app.db.models.UUID(), nullable=False),
    sa.Column('model_id', app.db.models.UUID(), nullable=False),
    sa.Column('submission_token', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('error', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_model_id'), 'jobs', ['model_id'], unique=False)
    op.create_index(op.f('ix_jobs_submission_token'), 'jobs', ['submission_token'], unique=True)
    op.create_table('model_explanations',
    sa.Column('id', app.db.models.UUID(), nullable=False),
    sa.Column('model_id', app.db.models.UUID(), nullable=False),
    sa.Column('computed_at', sa.DateTime(), nullable=True),
    sa.Column('feature_importances', app.db.models.PortableJSON(), nullable=False),
    sa.Column('top_drift_contributors', app.db.models.PortableJSON(), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_explanations_model_id'), 'model_explanations', ['model_id'], unique=False)
    op.create_table('model_versions',
    sa.Column('id', app.db.models.UUID(), nullable=False),
    sa.Column('model_id', app.db.models.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('artifact_url', sa.String(length=1024), nullable=True),
    sa.Column('framework', sa.String(length=100), nullable=True),
    sa.Column('parameters_count', sa.BigInteger(), nullable=True),
    sa.Column('training_dataset', sa.String(length=1024), nullable=True),
    sa.Column('governance_score', sa.Float(), nullable=True),
    sa.Column('risk_class', sa.String(length=20), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('metadata_json', app.db.models.PortableJSON(), nullable=True),
    sa.Column('created_by', app.db.models.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_versions_model_id'), 'model_versions', ['model_id'], unique=False)
    op.create_index('ix_model_versions_model_version', 'model_versions', ['model_id', 'version_number'], unique=True)
    op.create_table('nlp_intents',
    sa.Column('id', app.db.models.UUID(), nullable=False),
    sa.Column('model_id', app.db.models.UUID(), nullable=False),
    sa.Column('raw_intent', sa.String(length=1024), nullable=False),
    sa.Column('parsed_constraints', app.db.models.PortableJSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nlp_intents_model_id'), 'nlp_intents', ['model_id'], unique=False)
    op.create_table('notification_configs',
    sa.Column('id', app.db.models.UUID(), nullable=False),
    sa.Column('model_id', app.db.models.UUID(), nullable=False),
    sa.Column('slack_webhook_url', sa.String(length=512), nullable=True),
    sa.Column('slack_channel', sa.String(length=100), nullable=True),
    sa.Column('teams_webhook_url', sa.String(length=512), nullable=True),
    sa.Column('notify_on', app.db.models.PortableJSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_configs_model_id'), 'notification_configs', ['model_id'], unique=True)
    op.create_table('red_team_runs',
    sa.Column('id', app.db.models.UUID(), nullable=False),
    sa.Column('model_id', app.db.models.UUID(), nullable=True),
    sa.Column('run_at', sa.DateTime(), nullable=True),
    sa.Column('profile', sa.String(length=20), nullable=True),
    sa.Column('robustness_score', sa.Float(), nullable=True),
    sa.Column('attack_results', app.db.models.PortableJSON(), nullable=True),
    sa.Column('regressions_detected', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_red_team_runs_model_id'), 'red_team_runs', ['model_id'], unique=False)
    op.create_table('red_team_schedules',
    sa.Column('model_id', app.db.models.UUID(), nullable=False),
    sa.Column('schedule_cron', sa.String(length=100), nullable=True),
    sa.Column('attack_profile', sa.String(length=20), nullable=True),
    sa.Column('notification_on_regression', sa.Boolean(), nullable=True),
    sa.Column('baseline_robustness_score', sa.Float(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('model_id')
    )
    op.create_table('red_team_sessions',
    sa.Column('id', app.db.models.UUID(), nullable=False),
    sa.Column('model_id', app.db.models.UUID(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('total_attacks', sa.Integer(), nullable=True),
    sa.Column('success_count', sa.Integer(), nullable=True),
    sa.Column('metadata_json', app.db.models.PortableJSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_red_team_sessions_model_id'), 'red_team_sessions', ['model_id'], unique=False)
    op.create_table('report_cards',
    sa.Column('id', app.db.models.UUID(), nullable=False),
    sa.Column('model_id', app.db.models.UUID(), nullable=False),
    sa.Column('cert_hash', sa.String(length=64), nullable=False),
    sa.Column('issued_at', sa.DateTime(), nullable=True),
    sa.Column('overall_score', sa.Float(), nullable=False),
    sa.Column('verdict', sa.String(length=50), nullable=False),
    sa.Column('executive_summary', sa.Text(), nullable=True),
    sa.Column('metric_snapshots', app.db.models.PortableJSON(), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=True),
    sa.Column('revocation_reason', sa.String(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('pdf_path', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_cards_cert_hash'), 'report_cards', ['cert_hash'], unique=True)
    op.create_index(op.f('ix_report_cards_model_id'), 'report_cards', ['model_id'], unique=False)
    op.create_table('sandboxes',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('model_id', app.db.models.UUID(), nullable=True),
    sa.Column('container_id', sa.String(length=128), nullable=True),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sentinel_records',
    sa.Column('id', app.db.models.UUID(), nullable=False),
    sa.Column('model_id', app.db.models.UUID(), nullable=False),
    sa.Column('avg_psi', sa.Float(), nullable=False),
    sa.Column('feature_psi', app.db.models.PortableJSON(), nullable=True),
    sa.Column('window_size', sa.Integer(), nullable=True),
    sa.Column('threshold', sa.Float(), nullable=True),
    sa.Column('is_breached', sa.Boolean(), nullable=True),
    sa.Column('metadata_json', app.db.models.PortableJSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sentinel_records_created_at'), 'sentinel_records', ['created_at'], unique=False)
    op.create_index(op.f('ix_sentinel_records_model_id'), 'sentinel_records', ['model_id'], unique=False)
    op.create_table('dataset_versions',
    sa.Column('id', app.db.models.UUID(), nullable=False),
    sa.Column('dataset_id', app.db.models.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('storage_url', sa.String(length=1024), nullable=True),
    sa.Column('schema_hash', sa.String(length=128), nullable=True),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('feature_count', sa.Integer(), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('metadata_json', app.db.models.PortableJSON(), nullable=True),
    sa.Column('created_by', app.db.models.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dataset_versions_dataset_id'), 'dataset_versions', ['dataset_id'], unique=False)
    op.create_table('deployments',
    sa.Column('id', app.db.models.UUID(), nullable=False),
    sa.Column('version_id', app.db.models.UUID(), nullable=False),
    sa.Column('environment_id', app.db.models.UUID(), nullable=True),
    sa.Column('environment', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('deployed_by', app.db.models.UUID(), nullable=True),
    sa.Column('deployment_date', sa.DateTime(), nullable=True),
    sa.Column('metadata_json', app.db.models.PortableJSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['deployed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['environment_id'], ['environments.id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['model_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deployments_environment_id'), 'deployments', ['environment_id'], unique=False)
    op.create_index(op.f('ix_deployments_version_id'), 'deployments', ['version_id'], unique=False)
    op.create_table('drift_results',
    sa.Column('id', app.db.models.UUID(), nullable=False),
    sa.Column('model_id', app.db.models.UUID(), nullable=False),
    sa.Column('job_id', app.db.models.UUID(), nullable=False),
    sa.Column('computed_metrics_json', app.db.models.PortableJSON(), nullable=False),
    sa.Column('severity_counts', app.db.models.PortableJSON(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drift_results_job_id'), 'drift_results', ['job_id'], unique=False)
    op.create_index(op.f('ix_drift_results_model_id'), 'drift_results', ['model_id'], unique=False)
    op.create_table('fairness_results',
    sa.Column('id', app.db.models.UUID(), nullable=False),
    sa.Column('model_id', app.db.models.UUID(), nullable=False),
    sa.Column('job_id', app.db.models.UUID(), nullable=False),
    sa.Column('computed_metrics_json', app.db.models.PortableJSON(), nullable=False),
    sa.Column('severity_counts', app.db.models.PortableJSON(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fairness_results_job_id'), 'fairness_results', ['job_id'], unique=False)
    op.create_index(op.f('ix_fairness_results_model_id'), 'fairness_results', ['model_id'], unique=False)
    op.create_table('governance_results',
    sa.Column('id', app.db.models.UUID(), nullable=False),
    sa.Column('model_id', app.db.models.UUID(), nullable=False),
    sa.Column('job_id', app.db.models.UUID(), nullable=False),
    sa.Column('computed_metrics_json', app.db.models.PortableJSON(), nullable=False),
    sa.Column('severity_counts', app.db.models.PortableJSON(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_governance_results_job_id'), 'governance_results', ['job_id'], unique=False)
    op.create_index(op.f('ix_governance_results_model_id'), 'governance_results', ['model_id'], unique=False)
    op.create_table('guardrail_traces',
    sa.Column('id', app.db.models.UUID(), nullable=False),
    sa.Column('guardrail_id', app.db.models.UUID(), nullable=False),
    sa.Column('trace_id', sa.String(length=36), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('input_hash', sa.String(length=64), nullable=True),
    sa.Column('output_hash', sa.String(length=64), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('checks_summary', app.db.models.PortableJSON(), nullable=False),
    sa.Column('full_results', app.db.models.PortableJSON(), nullable=False),
    sa.ForeignKeyConstraint(['guardrail_id'], ['guardrail_configs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_guardrail_traces_guardrail_id'), 'guardrail_traces', ['guardrail_id'], unique=False)
    op.create_index(op.f('ix_guardrail_traces_timestamp'), 'guardrail_traces', ['timestamp'], unique=False)
    op.create_index(op.f('ix_guardrail_traces_trace_id'), 'guardrail_traces', ['trace_id'], unique=False)
    op.create_table('llm_results',
    sa.Column('id', app.db.models.UUID(), nullable=False),
    sa.Column('model_id', app.db.models.UUID(), nullable=False),
    sa.Column('job_id', app.db.models.UUID(), nullable=False),
    sa.Column('computed_metrics_json', app.db.models.PortableJSON(), nullable=False),
    sa.Column('severity_counts', app.db.models.PortableJSON(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_llm_results_job_id'), 'llm_results', ['job_id'], unique=False)
    op.create_index(op.f('ix_llm_results_model_id'), 'llm_results', ['model_id'], unique=False)
    op.create_table('performance_results',
    sa.Column('id', app.db.models.UUID(), nullable=False),
    sa.Column('model_id', app.db.models.UUID(), nullable=False),
    sa.Column('job_id', app.db.models.UUID(), nullable=False),
    sa.Column('computed_metrics_json', app.db.models.PortableJSON(), nullable=False),
    sa.Column('severity_counts', app.db.models.PortableJSON(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_performance_results_job_id'), 'performance_results', ['job_id'], unique=False)
    op.create_index(op.f('ix_performance_results_model_id'), 'performance_results', ['model_id'], unique=False)
    op.create_table('prediction_logs',
    sa.Column('id', app.db.models.UUID(), nullable=False),
    sa.Column('model_id', sa.String(length=255), nullable=False),
    sa.Column('model_version_id', app.db.models.UUID(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('features', app.db.models.PortableJSON(), nullable=True),
    sa.Column('prediction', sa.String(length=255), nullable=True),
    sa.Column('prediction_proba', sa.Float(), nullable=True),
    sa.Column('actual', sa.String(length=255), nullable=True),
    sa.Column('ground_truth', sa.String(length=255), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('data_source', sa.String(length=50), nullable=True),
    sa.Column('environment', sa.String(length=50), nullable=True),
    sa.Column('tags', app.db.models.PortableJSON(), nullable=True),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prediction_logs_model_id'), 'prediction_logs', ['model_id'], unique=False)
    op.create_index(op.f('ix_prediction_logs_model_version_id'), 'prediction_logs', ['model_version_id'], unique=False)
    op.create_index(op.f('ix_prediction_logs_timestamp'), 'prediction_logs', ['timestamp'], unique=False)
    op.create_index('ix_predlog_env', 'prediction_logs', ['environment'], unique=False)
    op.create_index('ix_predlog_model_ts', 'prediction_logs', ['model_id', 'timestamp'], unique=False)
    op.create_index('ix_predlog_version_ts', 'prediction_logs', ['model_version_id', 'timestamp'], unique=False)
    op.create_table('preflight_results',
    sa.Column('id', app.db.models.UUID(), nullable=False),
    sa.Column('model_id', app.db.models.UUID(), nullable=False),
    sa.Column('job_id', app.db.models.UUID(), nullable=False),
    sa.Column('computed_metrics_json', app.db.models.PortableJSON(), nullable=False),
    sa.Column('severity_counts', app.db.models.PortableJSON(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_preflight_results_job_id'), 'preflight_results', ['job_id'], unique=False)
    op.create_index(op.f('ix_preflight_results_model_id'), 'preflight_results', ['model_id'], unique=False)
    op.create_table('red_team_attacks',
    sa.Column('id', app.db.models.UUID(), nullable=False),
    sa.Column('session_id', app.db.models.UUID(), nullable=True),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('rounds', sa.Integer(), nullable=True),
    sa.Column('is_successful', sa.Boolean(), nullable=True),
    sa.Column('encrypted_prompt', sa.LargeBinary(), nullable=False),
    sa.Column('encrypted_response', sa.LargeBinary(), nullable=True),
    sa.Column('judge_reasoning', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['red_team_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_red_team_attacks_session_id'), 'red_team_attacks', ['session_id'], unique=False)
    op.create_table('scan_records',
    sa.Column('id', app.db.models.UUID(), nullable=False),
    sa.Column('model_id', app.db.models.UUID(), nullable=True),
    sa.Column('job_id', sa.String(length=50), nullable=True),
    sa.Column('scan_type', sa.String(length=50), nullable=False),
    sa.Column('policy_version_id', app.db.models.UUID(), nullable=True),
    sa.Column('checks_run', app.db.models.PortableJSON(), nullable=False),
    sa.Column('results_json', app.db.models.PortableJSON(), nullable=False),
    sa.Column('governance_score', sa.Float(), nullable=True),
    sa.Column('gate_status', sa.String(length=20), nullable=True),
    sa.Column('risk_score', sa.Integer(), nullable=True),
    sa.Column('risk_level', sa.String(length=20), nullable=True),
    sa.Column('top_drifted_features', app.db.models.PortableJSON(), nullable=True),
    sa.Column('fairness_metrics', app.db.models.PortableJSON(), nullable=True),
    sa.Column('bias_violation_flag', sa.Boolean(), nullable=True),
    sa.Column('fairness_risk_score', sa.Float(), nullable=True),
    sa.Column('artifact_url', sa.String(length=1024), nullable=True),
    sa.Column('training_dataset_url', sa.String(length=1024), nullable=True),
    sa.Column('validation_dataset_url', sa.String(length=1024), nullable=True),
    sa.Column('model_version_id', app.db.models.UUID(), nullable=True),
    sa.Column('security_checks', app.db.models.PortableJSON(), nullable=True),
    sa.Column('triggered_by', app.db.models.UUID(), nullable=True),
    sa.Column('trigger_source', sa.String(length=50), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], ),
    sa.ForeignKeyConstraint(['policy_version_id'], ['policy_versions.id'], ),
    sa.ForeignKeyConstraint(['triggered_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scan_records_job_id'), 'scan_records', ['job_id'], unique=False)
    op.create_index(op.f('ix_scan_records_model_id'), 'scan_records', ['model_id'], unique=False)
    op.create_table('alert_events',
    sa.Column('id', app.db.models.UUID(), nullable=False),
    sa.Column('rule_id', app.db.models.UUID(), nullable=False),
    sa.Column('scan_id', app.db.models.UUID(), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('delivered', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['rule_id'], ['alert_rules.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scan_id'], ['scan_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_events_rule_id'), 'alert_events', ['rule_id'], unique=False)
    op.create_table('experiments',
    sa.Column('id', app.db.models.UUID(), nullable=False),
    sa.Column('model_id', app.db.models.UUID(), nullable=False),
    sa.Column('dataset_version_id', app.db.models.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('parameters', app.db.models.PortableJSON(), nullable=True),
    sa.Column('metrics', app.db.models.PortableJSON(), nullable=True),
    sa.Column('artifact_url', sa.String(length=1024), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('training_time_ms', sa.Integer(), nullable=True),
    sa.Column('framework', sa.String(length=100), nullable=True),
    sa.Column('tags', app.db.models.PortableJSON(), nullable=True),
    sa.Column('created_by', app.db.models.UUID(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['dataset_version_id'], ['dataset_versions.id'], ),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_experiments_model_id'), 'experiments', ['model_id'], unique=False)
    op.create_table('explainability_results',
    sa.Column('id', app.db.models.UUID(), nullable=False),
    sa.Column('scan_id', app.db.models.UUID(), nullable=True),
    sa.Column('model_id', app.db.models.UUID(), nullable=False),
    sa.Column('method', sa.String(length=50), nullable=False),
    sa.Column('global_importance', app.db.models.PortableJSON(), nullable=True),
    sa.Column('local_explanations', app.db.models.PortableJSON(), nullable=True),
    sa.Column('summary_metrics', app.db.models.PortableJSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scan_id'], ['scan_records.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_explainability_results_model_id'), 'explainability_results', ['model_id'], unique=False)
    op.create_index(op.f('ix_explainability_results_scan_id'), 'explainability_results', ['scan_id'], unique=False)
    op.create_table('lineage_links',
    sa.Column('id', app.db.models.UUID(), nullable=False),
    sa.Column('dataset_version_id', app.db.models.UUID(), nullable=False),
    sa.Column('model_version_id', app.db.models.UUID(), nullable=False),
    sa.Column('training_run_id', app.db.models.UUID(), nullable=True),
    sa.Column('link_type', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_version_id'], ['dataset_versions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['training_run_id'], ['experiments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lineage_links_dataset_version_id'), 'lineage_links', ['dataset_version_id'], unique=False)
    op.create_index(op.f('ix_lineage_links_model_version_id'), 'lineage_links', ['model_version_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lineage_links_model_version_id'), table_name='lineage_links')
    op.drop_index(op.f('ix_lineage_links_dataset_version_id'), table_name='lineage_links')
    op.drop_table('lineage_links')
    op.drop_index(op.f('ix_explainability_results_scan_id'), table_name='explainability_results')
    op.drop_index(op.f('ix_explainability_results_model_id'), table_name='explainability_results')
    op.drop_table('explainability_results')
    op.drop_index(op.f('ix_experiments_model_id'), table_name='experiments')
    op.drop_table('experiments')
    op.drop_index(op.f('ix_alert_events_rule_id'), table_name='alert_events')
    op.drop_table('alert_events')
    op.drop_index(op.f('ix_scan_records_model_id'), table_name='scan_records')
    op.drop_index(op.f('ix_scan_records_job_id'), table_name='scan_records')
    op.drop_table('scan_records')
    op.drop_index(op.f('ix_red_team_attacks_session_id'), table_name='red_team_attacks')
    op.drop_table('red_team_attacks')
    op.drop_index(op.f('ix_preflight_results_model_id'), table_name='preflight_results')
    op.drop_index(op.f('ix_preflight_results_job_id'), table_name='preflight_results')
    op.drop_table('preflight_results')
    op.drop_index('ix_predlog_version_ts', table_name='prediction_logs')
    op.drop_index('ix_predlog_model_ts', table_name='prediction_logs')
    op.drop_index('ix_predlog_env', table_name='prediction_logs')
    op.drop_index(op.f('ix_prediction_logs_timestamp'), table_name='prediction_logs')
    op.drop_index(op.f('ix_prediction_logs_model_version_id'), table_name='prediction_logs')
    op.drop_index(op.f('ix_prediction_logs_model_id'), table_name='prediction_logs')
    op.drop_table('prediction_logs')
    op.drop_index(op.f('ix_performance_results_model_id'), table_name='performance_results')
    op.drop_index(op.f('ix_performance_results_job_id'), table_name='performance_results')
    op.drop_table('performance_results')
    op.drop_index(op.f('ix_llm_results_model_id'), table_name='llm_results')
    op.drop_index(op.f('ix_llm_results_job_id'), table_name='llm_results')
    op.drop_table('llm_results')
    op.drop_index(op.f('ix_guardrail_traces_trace_id'), table_name='guardrail_traces')
    op.drop_index(op.f('ix_guardrail_traces_timestamp'), table_name='guardrail_traces')
    op.drop_index(op.f('ix_guardrail_traces_guardrail_id'), table_name='guardrail_traces')
    op.drop_table('guardrail_traces')
    op.drop_index(op.f('ix_governance_results_model_id'), table_name='governance_results')
    op.drop_index(op.f('ix_governance_results_job_id'), table_name='governance_results')
    op.drop_table('governance_results')
    op.drop_index(op.f('ix_fairness_results_model_id'), table_name='fairness_results')
    op.drop_index(op.f('ix_fairness_results_job_id'), table_name='fairness_results')
    op.drop_table('fairness_results')
    op.drop_index(op.f('ix_drift_results_model_id'), table_name='drift_results')
    op.drop_index(op.f('ix_drift_results_job_id'), table_name='drift_results')
    op.drop_table('drift_results')
    op.drop_index(op.f('ix_deployments_version_id'), table_name='deployments')
    op.drop_index(op.f('ix_deployments_environment_id'), table_name='deployments')
    op.drop_table('deployments')
    op.drop_index(op.f('ix_dataset_versions_dataset_id'), table_name='dataset_versions')
    op.drop_table('dataset_versions')
    op.drop_index(op.f('ix_sentinel_records_model_id'), table_name='sentinel_records')
    op.drop_index(op.f('ix_sentinel_records_created_at'), table_name='sentinel_records')
    op.drop_table('sentinel_records')
    op.drop_table('sandboxes')
    op.drop_index(op.f('ix_report_cards_model_id'), table_name='report_cards')
    op.drop_index(op.f('ix_report_cards_cert_hash'), table_name='report_cards')
    op.drop_table('report_cards')
    op.drop_index(op.f('ix_red_team_sessions_model_id'), table_name='red_team_sessions')
    op.drop_table('red_team_sessions')
    op.drop_table('red_team_schedules')
    op.drop_index(op.f('ix_red_team_runs_model_id'), table_name='red_team_runs')
    op.drop_table('red_team_runs')
    op.drop_index(op.f('ix_notification_configs_model_id'), table_name='notification_configs')
    op.drop_table('notification_configs')
    op.drop_index(op.f('ix_nlp_intents_model_id'), table_name='nlp_intents')
    op.drop_table('nlp_intents')
    op.drop_index('ix_model_versions_model_version', table_name='model_versions')
    op.drop_index(op.f('ix_model_versions_model_id'), table_name='model_versions')
    op.drop_table('model_versions')
    op.drop_index(op.f('ix_model_explanations_model_id'), table_name='model_explanations')
    op.drop_table('model_explanations')
    op.drop_index(op.f('ix_jobs_submission_token'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_model_id'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_guardrail_configs_model_id'), table_name='guardrail_configs')
    op.drop_table('guardrail_configs')
    op.drop_index(op.f('ix_datasets_model_id'), table_name='datasets')
    op.drop_table('datasets')
    op.drop_index(op.f('ix_alerts_timestamp'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_model_id'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_aibom_model_id'), table_name='aibom')
    op.drop_index(op.f('ix_aibom_aibom_hash'), table_name='aibom')
    op.drop_table('aibom')
    op.drop_index(op.f('ix_models_project_id'), table_name='models')
    op.drop_index(op.f('ix_models_name'), table_name='models')
    op.drop_index(op.f('ix_models_fingerprint'), table_name='models')
    op.drop_table('models')
    op.drop_index(op.f('ix_contract_breaches_model_id'), table_name='contract_breaches')
    op.drop_index(op.f('ix_contract_breaches_contract_id'), table_name='contract_breaches')
    op.drop_index('ix_breach_model_ts', table_name='contract_breaches')
    op.drop_table('contract_breaches')
    op.drop_index(op.f('ix_agent_traces_session_id'), table_name='agent_traces')
    op.drop_index(op.f('ix_agent_traces_agent_id'), table_name='agent_traces')
    op.drop_table('agent_traces')
    op.drop_index(op.f('ix_usage_events_timestamp'), table_name='usage_events')
    op.drop_index(op.f('ix_usage_events_org_id'), table_name='usage_events')
    op.drop_index(op.f('ix_usage_events_event_type'), table_name='usage_events')
    op.drop_table('usage_events')
    op.drop_index(op.f('ix_projects_org_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_policy_versions_org_id'), table_name='policy_versions')
    op.drop_table('policy_versions')
    op.drop_index(op.f('ix_model_contracts_model_id'), table_name='model_contracts')
    op.drop_index('ix_contract_model_active', table_name='model_contracts')
    op.drop_table('model_contracts')
    op.drop_index(op.f('ix_llm_scan_records_prompt_hash'), table_name='llm_scan_records')
    op.drop_table('llm_scan_records')
    op.drop_table('credential_configs')
    op.drop_index(op.f('ix_audit_logs_org_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_table('agents')
    op.drop_index(op.f('ix_users_org_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_policy_rules_org_id'), table_name='policy_rules')
    op.drop_table('policy_rules')
    op.drop_index(op.f('ix_environments_org_id'), table_name='environments')
    op.drop_table('environments')
    op.drop_index(op.f('ix_ci_integrations_org_id'), table_name='ci_integrations')
    op.drop_table('ci_integrations')
    op.drop_index(op.f('ix_api_keys_org_id'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_key_hash'), table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_index(op.f('ix_alert_rules_org_id'), table_name='alert_rules')
    op.drop_table('alert_rules')
    op.drop_index(op.f('ix_retraining_events_policy_id'), table_name='retraining_events')
    op.drop_index(op.f('ix_retraining_events_model_id'), table_name='retraining_events')
    op.drop_table('retraining_events')
    op.drop_index(op.f('ix_organizations_stripe_customer_id'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.drop_table('organizations')
    op.drop_table('subscription_plans')
    op.drop_index(op.f('ix_stream_drift_records_model_id'), table_name='stream_drift_records')
    op.drop_table('stream_drift_records')
    op.drop_index(op.f('ix_retraining_policies_model_id'), table_name='retraining_policies')
    op.drop_table('retraining_policies')
    op.drop_index(op.f('ix_rag_traces_timestamp'), table_name='rag_traces')
    op.drop_index(op.f('ix_rag_traces_model_id'), table_name='rag_traces')
    op.drop_table('rag_traces')
    op.drop_index('ix_perfsnapshot_model_ts', table_name='performance_snapshots')
    op.drop_index(op.f('ix_performance_snapshots_model_id'), table_name='performance_snapshots')
    op.drop_index(op.f('ix_performance_snapshots_computed_at'), table_name='performance_snapshots')
    op.drop_table('performance_snapshots')
    op.drop_index(op.f('ix_embedding_batches_timestamp'), table_name='embedding_batches')
    op.drop_index(op.f('ix_embedding_batches_model_id'), table_name='embedding_batches')
    op.drop_index(op.f('ix_embedding_batches_batch_id'), table_name='embedding_batches')
    op.drop_table('embedding_batches')
    op.drop_index('ix_driftreport_model_ts', table_name='drift_reports')
    op.drop_index(op.f('ix_drift_reports_model_id'), table_name='drift_reports')
    op.drop_index(op.f('ix_drift_reports_created_at'), table_name='drift_reports')
    op.drop_table('drift_reports')
    op.drop_table('dataset_registry')
    # ### end Alembic commands ###
